---
title: "Tuesday Morning Exercise"
author: "Boyko Amarov"
date: "3/2/2021"
output: html_document
---

# Introduction to R

Show several arithmetic operations in R together with variable assignment.

We write code within `code chunks`.

```{r}
## Simple arithmetic operations.
1 + 2
23 / 7
2 * 45
2 ^ 4
```
## Variable assignment

Numeric values
```{r}
## Assignment operator <-
## Shortcut in R studio: Alt -

x <- 2
x + 2
x1 <- 43
x / x1
```
Character values

```{r}
y <- "some text value"
```

```{r}
# x + y
```
```{r}
# Lines starting with # in R code are comments (not executed)
# z <- Y
# Error: object 'Y' not found
```

## Logical values

```{r}
z1 <- TRUE
z2 <- FALSE
```

Logical values are commonly returned by logical comparisons.
```{r}
"Bob" == "Bob1"
```

```{r}
3 > 5
```

R code is case sensitive.

## First data set

```{r}
## Run install.packages only one for a package
install.packages("tidyverse")
```

```{r}
## Load packages
library(tidyverse)
```

We use `data.frame`s to store table data.

```{r}
earnings <- read.csv("https://raw.githubusercontent.com/feb-uni-sofia/econometrics2021/main/data/earnings.csv")
```

```{r}
glimpse(earnings)
```
