---
title: "Week4"
author: "Boyko Amarov"
date: "3/30/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
invoices <- read.delim('https://raw.githubusercontent.com/feb-uni-sofia/econometrics2020-solutions/master/data/invoices.txt')
```

```{r}
glimpse(invoices)
```

Datenbeschreibung:

- `Day` (numeric): Tag der Beobachtung
- `Invoices` (numeric): Zahl der eingegangenen Rechnungen
- `Time` (numeric): Bearbeitungszeit (Stunden)



```{r}
summary(invoices$Time)
```


```{r}
ggplot(data = invoices, aes(x = Invoices, y = Time)) + 
  geom_point() +
  labs(
    x = "Anzahl von Rechnungen",
    y = "Bearbeitungszeit"
  )+
  geom_vline(xintercept = 120, lty = 2, alpha = 1) +
  geom_vline(xintercept = c(80, 250), lty = 2, alpha = 0.3) +
  geom_hline(yintercept = mean(invoices$Time)) +
  geom_abline(intercept = 0, slope = 0.015, color = "steelblue2")
  # geom_abline(intercept = 0.64, slope = 0.011, color = "firebrick4")
```

Schätzung für die Bearbeitungszeit, die das Unternehmen für 80, 120, 250

Schätzung für 120 Rechnungen?


$$
i = 1,\ldots,n = 30 \text{ Tage} \\
x_i: \text{ Anzahl von Rechnungen an Tag } i \\
y_i: \text{ Bearbeitungszeit an Tag } i \\
$$
$$
y [\text{Stunden}] = \underbrace{0}_{\text{Achsenabschnitt (intercept)}}[\text{Stunden}] + \underbrace{0.015}_{\text{Steigung (slope)}}[\frac{\text{Stunden}}{\text{Rechnung}}] x [\text{Anzahl Rechnungen}]
$$

$$
\hat{y}_{x = 120} = 0 + 0.015 \times 120 = 1.8 \text{ (Stunden)}
$$
$$
\hat{y}_{x = 80} = 0 + 0.015 \times 80 = 1.2 \text{ (Stunden)}
$$


$$
y_i = \underbrace{\alpha + \beta x_i}_{\text{Gerade}} + \underbrace{e_i}_{\text{Abweichung von der Gerade für Tag i}}
$$
